import { readFile, writeFile } from "node:fs/promises";
import { relative } from "node:path";
import { fileURLToPath } from "node:url";

import openapiTS, { astToString } from "openapi-typescript";
import { format } from "prettier";
import { parse } from "yaml";

const packageDirectory = fileURLToPath(new URL("../", import.meta.url));
const sourcePath = fileURLToPath(new URL("../openapi.yaml", import.meta.url));
const jsonPath = fileURLToPath(
  new URL("../src/openapi.generated.json", import.meta.url),
);
const typesPath = fileURLToPath(
  new URL("../src/openapi.generated.d.ts", import.meta.url),
);
const checkOnly = process.argv.includes("--check");

function sortObject(value) {
  if (Array.isArray(value)) return value.map(sortObject);
  if (value === null || typeof value !== "object") return value;

  return Object.fromEntries(
    Object.entries(value)
      .sort(([left], [right]) => (left < right ? -1 : left > right ? 1 : 0))
      .map(([key, child]) => [key, sortObject(child)]),
  );
}

function assertLocalRefs(value, location = "$") {
  if (Array.isArray(value)) {
    value.forEach((child, index) =>
      assertLocalRefs(child, `${location}[${index}]`),
    );
    return;
  }
  if (value === null || typeof value !== "object") return;

  for (const [key, child] of Object.entries(value)) {
    const childLocation = `${location}.${key}`;
    if (
      key === "$ref" &&
      (typeof child !== "string" || !child.startsWith("#/"))
    ) {
      throw new Error(`External or invalid $ref at ${childLocation}`);
    }
    assertLocalRefs(child, childLocation);
  }
}

async function createOutputs() {
  const source = await readFile(sourcePath, "utf8");
  const parsed = parse(source);
  if (parsed?.openapi !== "3.1.0") {
    throw new Error("openapi.yaml must declare OpenAPI 3.1.0");
  }

  assertLocalRefs(parsed);
  const document = sortObject(parsed);
  const json = await format(JSON.stringify(document), { parser: "json" });
  const ast = await openapiTS(document, { alphabetize: true });
  const types = await format(
    [
      "/**",
      " * Generated from openapi.yaml by scripts/generate-openapi.mjs.",
      " * Do not edit this file directly.",
      " */",
      "",
      astToString(ast).trimEnd(),
      "",
    ].join("\n"),
    { parser: "typescript" },
  );

  return new Map([
    [jsonPath, json],
    [typesPath, types],
  ]);
}

async function checkOutputs(outputs) {
  const stale = [];
  for (const [outputPath, expected] of outputs) {
    let actual;
    try {
      actual = await readFile(outputPath, "utf8");
    } catch {
      stale.push(outputPath);
      continue;
    }
    if (actual !== expected) stale.push(outputPath);
  }

  if (stale.length > 0) {
    const relativePaths = stale.map((path) => relative(packageDirectory, path));
    process.stderr.write(
      `Generated OpenAPI files are stale: ${relativePaths.join(", ")}\nRun pnpm openapi:generate.\n`,
    );
    process.exitCode = 1;
  }
}

const outputs = await createOutputs();
if (checkOnly) {
  await checkOutputs(outputs);
} else {
  await Promise.all(
    [...outputs].map(([outputPath, contents]) =>
      writeFile(outputPath, contents),
    ),
  );
}
