/**
 * Generated from openapi.yaml by scripts/generate-openapi.mjs.
 * Do not edit this file directly.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get service health
     * @description Reports whether the commerce API is ready to serve traffic.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description The service is healthy. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["HealthStatus"];
          };
        };
        /** @description The service is not ready to serve traffic. */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["HealthStatus"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/openapi.json": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get the OpenAPI contract
     * @description Returns the canonical OpenAPI document served by this API.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description The canonical OpenAPI 3.1 document. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["OpenApiDocument"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/inventory": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List inventory
     * @description Lists bounded inventory records for an authenticated administrator.
     */
    get: operations["listInventory"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/inventory/{variantId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Set an inventory level
     * @description Sets the desired absolute on-hand quantity for a variant. expectedVersion provides optimistic concurrency control and must match the current record version. Quantity is never interpreted as an adjustment.
     */
    put: operations["setInventoryLevel"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/products/{productId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update a product
     * @description Updates mutable catalog fields for a product.
     */
    patch: operations["updateProduct"];
    trace?: never;
  };
  "/api/v1/cart": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get the current cart
     * @description Gets the cart belonging to the authenticated customer.
     */
    get: operations["getCurrentCart"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/cart/items/{variantId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Set a cart item quantity
     * @description Sets the desired absolute quantity for a variant in the authenticated customer's cart. A quantity of zero removes the item. This operation never interprets quantity as an increment or decrement.
     */
    put: operations["setCartItemQuantity"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/orders": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List current customer orders
     * @description Lists orders belonging to the authenticated customer.
     */
    get: operations["listCurrentCustomerOrders"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/orders/{orderNumber}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a current customer order
     * @description Gets an order by number only when it belongs to the authenticated customer.
     */
    get: operations["getCurrentCustomerOrder"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/products": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List products
     * @description Lists active products for web and customer callers. Admin callers can also see draft and archived products.
     */
    get: operations["listProducts"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/products/{slug}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a product
     * @description Gets an active product by slug for web and customer callers. Admin callers can also retrieve draft and archived products.
     */
    get: operations["getProduct"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ApiError: {
      /** @enum {string} */
      code:
        | "BAD_REQUEST"
        | "UNAUTHORIZED"
        | "FORBIDDEN"
        | "NOT_FOUND"
        | "CONFLICT - OUT_OF_STOCK - VERSION_MISMATCH - COMMERCE_UNAVAILABLE";
      message: string;
      requestId: string;
    };
    Cart: {
      id: string;
      itemCount: number;
      items: components["schemas"]["CartItem"][];
      subtotal: components["schemas"]["Money"];
      /** Format: date-time */
      updatedAt: string;
      version: number;
    };
    CartItem: {
      /** Format: uri */
      imageUrl: string | null;
      lineTotal: components["schemas"]["Money"];
      productName: string;
      productSlug: string;
      quantity: number;
      sku: string;
      unitPrice: components["schemas"]["Money"];
      variantId: string;
      variantName: string;
    };
    ErrorResponse: {
      error: components["schemas"]["ApiError"];
    };
    HealthStatus: {
      /** @enum {string} */
      status: "ok" | "degraded";
      /** Format: date-time */
      timestamp: string;
      version: string;
    };
    InventoryItem: {
      availableQuantity: number;
      lowStockThreshold: number;
      productId: string;
      productName: string;
      /** @description Absolute on-hand quantity. */
      quantity: number;
      reservedQuantity: number;
      sku: string;
      /** @enum {string} */
      state?: "in_stock" | "low_stock" | "out_of_stock" | "backorder";
      /** Format: date-time */
      updatedAt: string;
      variantId: string;
      variantName: string;
      version: number;
    };
    InventoryPage: {
      items: components["schemas"]["InventoryItem"][];
      nextCursor: string | null;
    };
    Money: {
      /** @description Monetary amount in the currency's minor unit. */
      amount: number;
      /** @description ISO 4217 currency code. */
      currency: string;
    };
    /** @description A bounded top-level representation of the served OpenAPI document. */
    OpenApiDocument: {
      components?: {
        [key: string]: unknown;
      };
      info: components["schemas"]["OpenApiInfo"];
      /** @constant */
      openapi: "3.1.0";
      paths: {
        [key: string]: {
          [key: string]: unknown;
        };
      };
      security?: components["schemas"]["OpenApiSecurityRequirement"][];
      servers?: components["schemas"]["OpenApiServer"][];
      tags?: components["schemas"]["OpenApiTag"][];
    } & {
      [key: string]: unknown;
    };
    OpenApiInfo: {
      description?: string;
      title: string;
      version: string;
    };
    OpenApiSecurityRequirement: {
      [key: string]: string[];
    };
    OpenApiServer: {
      url: string;
    };
    OpenApiTag: {
      description?: string;
      name: string;
    };
    Order: {
      items: components["schemas"]["OrderItem"][];
      orderNumber: string;
      /** Format: date-time */
      placedAt: string;
      shipping: components["schemas"]["Money"];
      /** @enum {string} */
      status:
        | "pending"
        | "confirmed"
        | "processing"
        | "shipped"
        | "delivered"
        | "cancelled";
      subtotal: components["schemas"]["Money"];
      tax: components["schemas"]["Money"];
      total: components["schemas"]["Money"];
      /** Format: date-time */
      updatedAt: string;
    };
    OrderItem: {
      lineTotal: components["schemas"]["Money"];
      productName: string;
      productSlug: string;
      quantity: number;
      sku: string;
      unitPrice: components["schemas"]["Money"];
      variantId: string;
      variantName: string;
    };
    OrderPage: {
      items: components["schemas"]["Order"][];
      nextCursor: string | null;
    };
    Product: {
      category: string;
      /** Format: date-time */
      createdAt: string;
      description: string;
      id: string;
      images: components["schemas"]["ProductImage"][];
      name: string;
      slug: string;
      /** @enum {string} */
      status: "draft" | "active" | "archived";
      /** Format: date-time */
      updatedAt: string;
      variants: components["schemas"]["ProductVariant"][];
    };
    ProductImage: {
      alt: string;
      /** Format: uri-reference */
      url: string;
    };
    ProductOption: {
      name: string;
      value: string;
    };
    ProductPage: {
      items: components["schemas"]["Product"][];
      nextCursor: string | null;
    };
    ProductVariant: {
      availableQuantity: number;
      id: string;
      name: string;
      options: components["schemas"]["ProductOption"][];
      price: components["schemas"]["Money"];
      sku: string;
    };
    SetCartItemQuantityInput: {
      /** @description Desired final cart quantity. Zero removes the item. */
      quantity: number;
    };
    SetInventoryLevelInput: {
      /** @description Inventory version observed before this update. */
      expectedVersion: number;
      /** @description Desired final on-hand quantity, not an adjustment. */
      quantity: number;
    };
    UpdateProductInput: {
      category?: string;
      description?: string;
      imageUrls?: string[];
      name?: string;
      /** @enum {string} */
      status?: "draft" | "active" | "archived";
    };
  };
  responses: {
    /** @description The request is malformed or fails validation. */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description The request conflicts with current inventory or resource state. */
    Conflict: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description The authenticated principal cannot perform this operation. */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description The requested resource does not exist or is not visible to the caller. */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description The service could not complete the request. */
    ServerError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
    /** @description A valid bearer token is required. */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
  };
  parameters: {
    /** @description Exact category slug to include. */
    CategoryQuery: string;
    /** @description Opaque cursor returned by a previous page. */
    CursorQuery: string;
    /** @description When true, only include products with an available variant. */
    InStockQuery: boolean;
    /** @description Maximum number of records to return. */
    LimitQuery: number;
    /** @description When true, only include inventory at or below its threshold. */
    LowStockQuery: boolean;
    /** @description Customer-facing order number. */
    OrderNumberPath: string;
    /** @description Stable product identifier. */
    ProductIdPath: string;
    /** @description Case-insensitive product name, slug, or SKU search text. */
    SearchQuery: string;
    /** @description Public product slug. */
    SlugPath: string;
    /** @description Stable product variant identifier. */
    VariantIdPath: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listInventory: {
    parameters: {
      query?: {
        /** @description Opaque cursor returned by a previous page. */
        cursor?: components["parameters"]["CursorQuery"];
        /** @description Maximum number of records to return. */
        limit?: components["parameters"]["LimitQuery"];
        /** @description When true, only include inventory at or below its threshold. */
        lowStock?: components["parameters"]["LowStockQuery"];
        /** @description Case-insensitive product name, slug, or SKU search text. */
        query?: components["parameters"]["SearchQuery"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A bounded page of inventory records. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InventoryPage"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      500: components["responses"]["ServerError"];
    };
  };
  setInventoryLevel: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Stable product variant identifier. */
        variantId: components["parameters"]["VariantIdPath"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetInventoryLevelInput"];
      };
    };
    responses: {
      /** @description The updated inventory record with its new version. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InventoryItem"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
      500: components["responses"]["ServerError"];
    };
  };
  updateProduct: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Stable product identifier. */
        productId: components["parameters"]["ProductIdPath"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProductInput"];
      };
    };
    responses: {
      /** @description The updated product. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Product"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      500: components["responses"]["ServerError"];
    };
  };
  getCurrentCart: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The authenticated customer's cart. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Cart"];
        };
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      500: components["responses"]["ServerError"];
    };
  };
  setCartItemQuantity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Stable product variant identifier. */
        variantId: components["parameters"]["VariantIdPath"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetCartItemQuantityInput"];
      };
    };
    responses: {
      /** @description The updated cart. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Cart"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
      500: components["responses"]["ServerError"];
    };
  };
  listCurrentCustomerOrders: {
    parameters: {
      query?: {
        /** @description Opaque cursor returned by a previous page. */
        cursor?: components["parameters"]["CursorQuery"];
        /** @description Maximum number of records to return. */
        limit?: components["parameters"]["LimitQuery"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A bounded page of the authenticated customer's orders. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrderPage"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      500: components["responses"]["ServerError"];
    };
  };
  getCurrentCustomerOrder: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Customer-facing order number. */
        orderNumber: components["parameters"]["OrderNumberPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The requested customer order. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Order"];
        };
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      500: components["responses"]["ServerError"];
    };
  };
  listProducts: {
    parameters: {
      query?: {
        /** @description Exact category slug to include. */
        category?: components["parameters"]["CategoryQuery"];
        /** @description Opaque cursor returned by a previous page. */
        cursor?: components["parameters"]["CursorQuery"];
        /** @description When true, only include products with an available variant. */
        inStock?: components["parameters"]["InStockQuery"];
        /** @description Maximum number of records to return. */
        limit?: components["parameters"]["LimitQuery"];
        /** @description Case-insensitive product name, slug, or SKU search text. */
        query?: components["parameters"]["SearchQuery"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A bounded page of products. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductPage"];
        };
      };
      400: components["responses"]["BadRequest"];
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      500: components["responses"]["ServerError"];
    };
  };
  getProduct: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Public product slug. */
        slug: components["parameters"]["SlugPath"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The requested product. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Product"];
        };
      };
      401: components["responses"]["Unauthorized"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      500: components["responses"]["ServerError"];
    };
  };
}
